### ISSUE TITLE
Fixing citations

### ISSUE THREAD

**Issue by RobinCamarasa** [mlresearch/v172#2]
Dear @lawrennd ,

The citations were not properly compiled for `camasa22a/camarasa22a.pdf` available. I tried to do a pull request but apparently I cannot upload documents. Could you upload this corrected version: https://drive.google.com/file/d/16nHw7Ysp9cn_tQbZoQitOieaqpcU99LB/view?usp=sharing .

Thank you in advance.

Best,
Robin

**Comment by lawrennd** [comment]
HI Robin,

You should be able to change the PDF in your document and submit by pull request.

Neil

From: Robin Camarasa ***@***.***>
Date: Friday, 14 July 2023 at 01:47
To: mlresearch/v172 ***@***.***>
Cc: Neil Lawrence ***@***.***>, Mention ***@***.***>
Subject: [mlresearch/v172] Fixing citations (Issue #2)

Dear @lawrennd<https://github.com/lawrennd> ,

The citations were not properly compiled for camasa22a/camarasa22a.pdf available. I tried to do a pull request but apparently I cannot upload documents. Could you upload this corrected version: https://drive.google.com/file/d/16nHw7Ysp9cn_tQbZoQitOieaqpcU99LB/view?usp=sharing .

Thank you in advance.

Best,
Robin

**Comment by RobinCamarasa** [comment]
Hi @lawrennd ,

You are right, I did that in pull request #3 .

Best,
Robin
